### ISSUE TITLE
Webpack build not working in staging docker container

### ISSUE THREAD

**Issue by Kaptard** [nexus-devs/NexusHub#237]
**I'm submitting a...**

- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request

<br>

**Current behavior**

Error when loading page with `vue-tween-number` package, so the page won't load.

<br>

**Expected behavior**

Should load the page without errors.

<br>

**Minimal reproduction of the problem**

(Requires access to staging servers)
Launch docker stack, listen to `nexus_ui` service logs, visit [/warframe](https://staging.nexushub.co/warframe)

<br>

**Environment**

Browser: 
- [ ] Chrome (desktop) version:
- [ ] Chrome (Android) version:
- [ ] Chrome (iOS) version:
- [ ] Firefox version:
- [ ] Safari (desktop) version:
- [ ] Safari (iOS) version:
- [ ] IE version:
- [ ] Edge version:

For development issues:
- Node version: 10@latest
- Operating System: Alpine@LTS

##

**Additional Description**

Error log (truncated)
```
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    | TypeError: shifty.Tweenable is not a constructor
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at a.handler (/app/nexus-stats/node_modules/vue-tween-number/index.js:281:22)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at a.t.$watch (/app/nexus-stats/node_modules/vue/dist/vue.runtime.common.prod.js:6:33214)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at yn (/app/nexus-stats/node_modules/vue/dist/vue.runtime.common.prod.js:6:29798)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at /app/nexus-stats/node_modules/vue/dist/vue.runtime.common.prod.js:6:29284
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at pn (/app/nexus-stats/node_modules/vue/dist/vue.runtime.common.prod.js:6:29295)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at a.e._init (/app/nexus-stats/node_modules/vue/dist/vue.runtime.common.prod.js:6:32700)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at new a (/app/nexus-stats/node_modules/vue/dist/vue.runtime.common.prod.js:6:30340)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at Vi (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:66367)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at io (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:70597)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at ro (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:70270)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at _t.eo [as renderNode] (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:67517)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at _t.next (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:20536)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at _t.n [as write] (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:18748)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at _t.eo [as renderNode] (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:69295)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at _t.next (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:20536)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at _t.n [as write] (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:18748)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at _t.next (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:20619)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at _t.n [as write] (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:18748)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at _t.eo [as renderNode] (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:69295)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at _t.next (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:20536)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at n (/app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:18748)
nexus_ui.1.jq4ecap3tuv8@nexus-staging-00    |     at /app/nexus-stats/node_modules/vue-server-renderer/build.prod.js:1:68628
```

**Comment by Kaptard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix(staging): Resolve webpack builds not working on staging docker container](https://trello.com/c/kwhGjpt9/2-fixstaging-resolve-webpack-builds-not-working-on-staging-docker-container)

**Comment by Kaptard** [comment]
Ditched `node:10-alpine` in favor of `node:10` as base image since these errors were the result of bad npm installs.
